require:
  - rubocop-rails

AllCops:
  Exclude:
    - 'bin/**/*'
    - 'coverage/**/*'
    - 'log/**/*'
    - 'node_modules/**/*'
    - 'project_requirements/**/*'
    - 'tmp/**/*'
    - 'vendor/**/*'
    - 'config/application.rb'
    - 'config/boot.rb'
    - 'config/environments/**/*'
    - 'config/environment.rb'
    - 'config/puma.rb'
    - 'config/spring.rb'
    - 'config/initializers/**/*'
    - 'spec/**/*'
  NewCops: enable

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Rails/UniqueValidationWithoutIndex:
  Enabled: false

Metrics/MethodLength:
  Max: 25

Naming/VariableNumber:
  Enabled: false
